-- Catálogo del libro, parte 5: los 50 alimentos libres.
--
-- Van con libre = true y sin conteo, salvo los que el libro condiciona: esos
-- llevan la condición en `nota` y, cuando ya no son libres, el conteo en las
-- columnas. El último de la lista (cremas en sobre) aparece entre los libres
-- del PDF pero cuesta ½ carbohidrato, así que va con libre = false.

insert into libro_alimentos
  (id, seccion_id, nombre, marcas, porcion, c, p, libre, nota, orden) values
  ('libre-001', 'libres', 'Konjac low calorie spaghetti',           array['Delga-C'],                          '65 g',            0, 0, true, null,  1),
  ('libre-002', 'libres', 'Konjac low calorie rice',                array['Delga-C'],                          '65 g',            0, 0, true, null,  2),
  ('libre-003', 'libres', 'Leche condensada sin azúcar',            array['Sweet Treats'],                     '2 cucharadas',    0, 0, true, null,  3),
  ('libre-004', 'libres', 'Suspiros sin azúcar',                    array['Sweet Treats'],                     '30 unidades',     0, 0, true, null,  4),
  ('libre-005', 'libres', 'Sirope de maple sin azúcar',             array['Savoré', 'Log Cabin'],              '¼ taza',          0, 0, true, null,  5),
  ('libre-006', 'libres', 'Helados minis',                          array['Nikkos'],                           '4 unidades',      0, 0, true, null,  6),
  ('libre-007', 'libres', 'Bebida hidratante',                      array['Suerox'],                           '625 ml',          0, 0, true, null,  7),
  ('libre-008', 'libres', 'Té frío Zero, diferentes sabores',       array['Fuze Tea'],                         null,              0, 0, true, null,  8),
  ('libre-009', 'libres', 'Té frío sin azúcar, diferentes sabores', array['Arizona Diet', 'Diet Snapple'],     null,              0, 0, true, null,  9),
  ('libre-010', 'libres', 'Té Cero, diferentes sabores',            array['Tropical'],                         null,              0, 0, true, null, 10),
  ('libre-011', 'libres', 'Té frío cero, diferentes variedades',    array['Dos Pinos'],                        null,              0, 0, true, null, 11),
  ('libre-012', 'libres', 'Agua mineral con gas',                   array['Perrier', 'San Pellegrino'],        null,              0, 0, true, null, 12),
  ('libre-013', 'libres', 'Agua mineral con gas saborizada sin azúcar', array['San Pellegrino'],               null,              0, 0, true, null, 13),
  ('libre-014', 'libres', 'Agua tónica o quinada sin azúcar',       '{}',                                      null,              0, 0, true, null, 14),
  ('libre-015', 'libres', 'Gaseosa Alma sparkling, varios sabores', array['Dos Pinos'],                        null,              0, 0, true, null, 15),
  ('libre-016', 'libres', 'Aloe vera light',                        array['Dos Pinos'],                        '1 botella',       0, 0, true, null, 16),
  ('libre-017', 'libres', 'Refrescos en polvo sin azúcar',          array['Clight', 'Livean', 'D-Lite', 'Lio Te Light'], null,    0, 0, true, null, 17),
  ('libre-018', 'libres', 'Bebida energética natural',              array['Rooster'],                          '1 unidad',        0, 0, true, null, 18),
  ('libre-019', 'libres', 'Bebidas con gas saborizadas sin azúcar', array['Sparkling ICE', 'ICE Caffeine', 'H2OH'], null,         0, 0, true, null, 19),
  ('libre-020', 'libres', 'Bebidas energéticas sin azúcar',         array['Red Bull Sugar Free', 'Jet Cero', 'Maxxx Energy Zero', 'Monster Zero'], '1 unidad', 0, 0, true, null, 20),
  ('libre-021', 'libres', 'Sustitutos de azúcar',                   '{}',                                      null,              0, 0, true, null, 21),
  ('libre-022', 'libres', 'Jalea sin azúcar',                       array['Delga-C', 'Ujarrás Sugar Free', 'Sweetwell', 'Hero 0% azúcar', 'Tricopilia Light'], '2 cucharadas', 0, 0, true, null, 22),
  ('libre-023', 'libres', 'Suspiros, varios sabores',               array['Sweetwell'],                        '15 unidades',     0, 0, true, null, 23),
  ('libre-024', 'libres', 'Chips de chocolate de leche y amargo',   array['Sweetwell'],                        '5 g',             0, 0, true, null, 24),
  ('libre-025', 'libres', 'Chocolate sugar free, diferentes variedades', array['Hershey''s'],                  '1 unidad',        0, 0, true, null, 25),
  ('libre-026', 'libres', 'Chocolate en polvo sin azúcar',          array['Cocoa Dulce Light', 'Cacao Amargo', 'Hershey''s Sugar Free'], '2 cucharaditas', 0, 0, true, null, 26),
  ('libre-027', 'libres', 'Sirope de kola light',                   array['La Mundial', 'La Flor'],            '1/3 taza',        0, 0, true, null, 27),
  ('libre-028', 'libres', 'Crema para café liviana',                '{}',                                      '2 cucharaditas',  0, 0, true,
   '2 cucharaditas al día son libres. 4 cucharaditas cuentan ½ carbohidrato.',                                                                  28),
  ('libre-029', 'libres', 'Gelatina sin azúcar',                    array['Diet X'],                           '2 tazas preparadas', 0, 0, true, null, 29),
  ('libre-030', 'libres', 'Gelatina preparada sin azúcar',          array['Gelakin'],                          '1 unidad',        0, 0, true, null, 30),
  ('libre-031', 'libres', 'Confites sin azúcar',                    '{}',                                      '3 unidades',      0, 0, true, null, 31),
  ('libre-032', 'libres', 'Goma de mascar sin azúcar',              '{}',                                      '5 unidades',      0, 0, true, null, 32),
  ('libre-033', 'libres', 'Helados bajos en calorías Frutibarras o Yogupaletas', array['Nikkos'],              '1 unidad',        0, 0, true, null, 33),
  ('libre-034', 'libres', 'Sobre en polvo para preparar arroz con leche y flan', '{}',                         '1 unidad',        0, 0, true, null, 34),
  ('libre-035', 'libres', 'Café, todos los tuestes',                '{}',                                      null,              0, 0, true, null, 35),
  ('libre-036', 'libres', 'Té verde y té de bolsitas',              '{}',                                      null,              0, 0, true, null, 36),
  ('libre-037', 'libres', 'Té negro',                               '{}',                                      null,              0, 0, true, null, 37),
  ('libre-038', 'libres', 'Té chai',                                '{}',                                      null,              0, 0, true, null, 38),
  ('libre-039', 'libres', 'Aceites en spray, cualquier marca',      '{}',                                      null,              0, 0, true,
   'No usar más de 3 segundos.',                                                                                                                39),
  ('libre-040', 'libres', 'Aderezos italianos o mostaza miel',      array['Delga-C'],                          '2 cucharadas',    0, 0, true, null, 40),
  ('libre-041', 'libres', 'Aderezo Thousand Islands, Ranch o asiático', array['Delga-C'],                      '1 cucharada',     0, 0, true,
   '1 cucharada al día es libre. 2 cucharadas cuentan ½ carbohidrato.',                                                                         41),
  ('libre-042', 'libres', 'Salsa de tomate',                        array['Delga-C'],                          '5 cucharadas',    0, 0, true, null, 42),
  ('libre-043', 'libres', 'Salsa de tomate de cualquier marca',     '{}',                                      '1 cucharada',     0, 0, true,
   '1 cucharada al día es libre. 2 cucharadas cuentan ½ carbohidrato.',                                                                         43),
  ('libre-044', 'libres', 'Mayonesa sin grasa',                     array['Delga-C'],                          '2.5 cucharadas',  0, 0, true, null, 44),
  ('libre-045', 'libres', 'Queso parmesano',                        '{}',                                      '1 cucharadita',   0, 0, true,
   '1 cucharadita al día es libre. 1 cucharada o 15 g cuentan ½ proteína.',                                                                     45),
  ('libre-046', 'libres', 'Queso crema light',                      '{}',                                      '2 cucharaditas',  0, 0, true, null, 46),
  ('libre-047', 'libres', 'Ajo, especias, hierbas, tabasco, sazón completo, condimentos, cubitos y sazonadores', '{}', null,      0, 0, true, null, 47),
  ('libre-048', 'libres', 'Jugo de limón',                          '{}',                                      '½ taza',          0, 0, true, null, 48),
  ('libre-049', 'libres', 'Caldos de pollo, res, pescado, frijol o verduras, caseros y sin grasa', '{}',        null,              0, 0, true, null, 49),
  ('libre-050', 'libres', 'Cremas, diferentes sabores',             '{}',                                      '1/5 de sobre',  0.5, 0, false,
   'Está en la lista de alimentos libres del libro, pero cuenta ½ carbohidrato.',                                                                50)
on conflict (id) do update set
  seccion_id = excluded.seccion_id, nombre = excluded.nombre,
  marcas = excluded.marcas, porcion = excluded.porcion,
  c = excluded.c, p = excluded.p, libre = excluded.libre,
  nota = excluded.nota, orden = excluded.orden;
